# Generated by Django 5.0.6 on 2024-09-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='admitcard_images/')),
                ('exam_type', models.CharField(choices=[('Midterm Examination', 'Midterm Examination'), ('Final Examination', 'Final Examination')], max_length=20)),
                ('semester_name', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=10)),
                ('program_name', models.CharField(choices=[('BSc in CSE', 'BSc in CSE'), ('BSc in EEE', 'BSc in EEE'), ('BBA', 'BBA'), ('MBA', 'MBA')], max_length=50)),
                ('batch_number', models.IntegerField()),
                ('courses', models.ManyToManyField(to='admitcard.course')),
            ],
        ),
    ]
