# Generated by Django 5.0.6 on 2024-09-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admitcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitcard',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
